import type { UiStoreState } from "./uiStore";
import type { WorkspaceStoreState } from "./workspaceStore";

export const uiSelectors = {
  trafficKeyword: (state: UiStoreState) => state.trafficKeyword,
  trafficMethod: (state: UiStoreState) => state.trafficMethod,
  trafficStatusCode: (state: UiStoreState) => state.trafficStatusCode,
  trafficHostOnly: (state: UiStoreState) => state.trafficHostOnly,
  trafficFocusMode: (state: UiStoreState) => state.trafficFocusMode,
  trafficInspectorTab: (state: UiStoreState) => state.trafficInspectorTab,
  trafficAutoRefresh: (state: UiStoreState) => state.trafficAutoRefresh,
  proxyGroupSearch: (state: UiStoreState) => state.proxyGroupSearch,
  proxyRuleSearch: (state: UiStoreState) => state.proxyRuleSearch,
  proxyFilterMode: (state: UiStoreState) => state.proxyFilterMode,
  proxySortMode: (state: UiStoreState) => state.proxySortMode,
  mockGroupSearch: (state: UiStoreState) => state.mockGroupSearch,
};

export const workspaceSelectors = {
  trafficSelectedRequestId: (state: WorkspaceStoreState) => state.trafficSelectedRequestId,
  trafficCertificateModalOpen: (state: WorkspaceStoreState) => state.trafficCertificateModalOpen,
  trafficSessionStartedAt: (state: WorkspaceStoreState) => state.trafficSessionStartedAt,
  proxyActiveGroupId: (state: WorkspaceStoreState) => state.proxyActiveGroupId,
  proxyMenuGroupId: (state: WorkspaceStoreState) => state.proxyMenuGroupId,
  proxyHeaderMenuOpen: (state: WorkspaceStoreState) => state.proxyHeaderMenuOpen,
  proxyCollapsedHosts: (state: WorkspaceStoreState) => state.proxyCollapsedHosts,
  proxyDrawerRule: (state: WorkspaceStoreState) => state.proxyDrawerRule,
  proxyEditingRule: (state: WorkspaceStoreState) => state.proxyEditingRule,
  proxyEditingGroup: (state: WorkspaceStoreState) => state.proxyEditingGroup,
  proxyRuleForm: (state: WorkspaceStoreState) => state.proxyRuleForm,
  proxyRuleModalOpen: (state: WorkspaceStoreState) => state.proxyRuleModalOpen,
  proxyGroupModalOpen: (state: WorkspaceStoreState) => state.proxyGroupModalOpen,
  proxySubmitting: (state: WorkspaceStoreState) => state.proxySubmitting,
  proxyGroupName: (state: WorkspaceStoreState) => state.proxyGroupName,
  mockSelectedGroup: (state: WorkspaceStoreState) => state.mockSelectedGroup,
  mockSelectedRuleId: (state: WorkspaceStoreState) => state.mockSelectedRuleId,
  mockEditingId: (state: WorkspaceStoreState) => state.mockEditingId,
  mockModalOpen: (state: WorkspaceStoreState) => state.mockModalOpen,
  mockGroupMenuName: (state: WorkspaceStoreState) => state.mockGroupMenuName,
  mockRuleMenuId: (state: WorkspaceStoreState) => state.mockRuleMenuId,
  mockCollapsedBlocks: (state: WorkspaceStoreState) => state.mockCollapsedBlocks,
  mockCustomGroups: (state: WorkspaceStoreState) => state.mockCustomGroups,
  mockGroupMeta: (state: WorkspaceStoreState) => state.mockGroupMeta,
  mockForm: (state: WorkspaceStoreState) => state.mockForm,
};
